### PR TITLE
Improve print styles

### LINKED ISSUE #70: Printer-friendly version
We want to reach as many people as possible with 'The Infi Way'. A subset of people will want to print the document. 

Currently, there are these issues:
1. Black background: in the print-outs Christa used when carrying out her Infi-way session, the background of the print was solid-black. This is tremendously wasteful for ink. (Note: I'm not sure how she made the prints, since in my tests the prints were always grey text on white background; I suspect she used screenshot because of issue 2. Need to ask her if necessary.)
2. Browsers mess up the printing in different ways: (all tested on my mac)
- Safari: huge font, lots of white space due to the column setup
- Firefox: big empty circles where the graphics would have been
- Chrome: big empty circles where the graphics would have been; plus rendering the printer preview for some reason takes ages

Solution suggestion:
In order to promote printing and PDF-sharing of the Infi-way, while printing (or PDF-exporting)
1. remove solidblack background (and adjust font-color accordingly, 
2. strip unnecessary graphics, 
3. render the information hierarchy without relying on columns (to prevent white-space)
4. use a 'normal' font-size
5. (print the full links, since this website is rather link-heavy so the print will loose quite some info?)

### PR DESCRIPTION
**Pull request by LucaScorpion**
Closes #70 

A couple of small changes were required in the normal styles, to ensure elements didn't fall outside of their defined height (thus being cut in half on page breaks). I've also extracted a duplicated height value to a CSS var. Other than that all styling is contained in a `@media print` block.

Note that the `-webkit-print-color-adjust` is specifically necessary, because Chrome doesn't respect the `print-color-adjust` property.

### CODE REVIEW

**Comment by yougotdirked** [comment]
LGTM

**Comment by LucaScorpion** [comment]
@jeroenheijmans Good feedback, thanks!

> Is there a way to have the CSS suggest the header ("The Infi Way" and the URL) are suppressed? Or is that browser behavior that's not in our control?

Turns out, there is kind of a way. I found this can be done using the `@page` rule. Using it does mean you _never_ get the print header and footer though, so it's not much of a suggestion :sweat_smile:  I don't think that's really an issue, but good to consider. I'll add it, and we can see what we think.

> Tiny nitpick: the icons near the numbers are white-on-black but inverted is nicer for prints I think?

Agreed yes, will do!

> Can we get the "Infi Test" fit on a single A4 page?

That would indeed be nicer, I can probably make that work by tightening some margins left and right.

>The footer is printed on its own final page, but styled the way it is on the website. Can we perhaps improve that a little bit still? Maybe give it a print-only section header, not center it, and possibly even make it more into a list or "colofon" style section?

Yess good idea. I'll see what I can make of that (though if you have specific ideas, those are ofc more than welcome)

**Comment by LucaScorpion** [comment]
Some updates: I've addressed all the points, and I'm pretty happy with how it looks now.

One note: I didn't end up doing the header/footer hiding "trick", since that also meant I'd have to ensure the page margins were okay for every page, which felt very finicky and error-prone. I did set a `@page` margin (so it's at least the same in all browsers). In Chrome this does seem to now always hide the header/footer, but not in FF.

Apart from that I wasn't _really_ sure what to do with the footer, so for now I just put the links below each other, left aligned. Already a bit better than what it was imo, but I'm open for suggestions there.

The current result:

[The Infi Way.pdf](https://github.com/infi-nl/the-infi-way/files/12342905/The.Infi.Way.pdf)

@jeroenheijmans What do you think? :)

**Comment by jeroenheijmans** [comment]
Loving it!

One final tiny thing would be that I'd worry about is that the first page is quite fragile to a regression, if in the future the contents change only a small amount it will already plop off the page. Take this contrived, small, but somewhat reasonable example: 

shows extra text to pop the infi test off page 1

If I tweaked a bit in the devtools (and use `!important` for a shortcut) then this would get the effect that I'd recommend:

```css
.topic-icon {
  margin: 0 !important;
  border: none !important!;
}

.infi-test ol li::before {
  border-radius: 0 !important;
}

.infi-test ol li {
  margin-bottom: 0 !important;
}
```

Which prints like this, leaving room for future changes:

infi test fitting on one page

All this is a small thing and I'd be okay too with going forward with the current version if priorities or energy levels are needed elsewhere 😅

**Review by jeroenheijmans — APPROVED** [review]

**Comment by LucaScorpion** [comment]
Ooh that's a great suggestion! I've updated the styles to match that, though I did leave the rounded corners for the numbering ;) That seemed a bit nicer to me. Final version for reference:

[The Infi Way.pdf](https://github.com/infi-nl/the-infi-way/files/12359738/The.Infi.Way.pdf)

And with that I'll just merge it! :rocket:

**Pull request merged**
