### PR TITLE
Language switching improvements

### PR DESCRIPTION
**Pull request by h-five-e**
Issue: https://github.com/infi-nl/the-infi-way/issues/38

### CODE REVIEW

**Comment by jeroenheijmans** [comment]
Big improvement already! Some minor thoughts:

- I'd like to stick with US English if a choice has to be made (at first glance saw no instances yet, but still), so the flag could be either the USA one, or one of them "half-half" flags that show both of them with diagonal bar. (I myself prefer the first option.)
- Are we good on the copyright and source of the icons?

And one major question, thinking out loud:

- Is it worth to do the language toggle at the top, possibly in a corner? Is the increased discoverability worth the extra clutter in the initial view? Or perhaps not.... (I honestly don't have the answer to these questions.) - and would we need to spend extra time on the design/ux/position of this if we go for a header-approach? (Also, either way, this PR might already be worth merging as is, making a move to the header a secondary thing in its own PR?)

**Comment by LucaScorpion** [comment]
Haven't had time to really dive into it yet, but looks good from what I can tell!

> Are we good on the copyright and source of the icons?

@jeroenheijmans  These are emoji, not images, so that should be fine :)

As for the discoverability of the language switcher, I agree somewhere at the top would be nicer (or at least more clear). But for now this is already a nice improvement imo.

**Comment by h-five-e** [comment]
> I'd like to stick with US English if a choice has to be made
I used what's already there, so just `en`. But your issue seems to be more with the flag. I am personally more in favour of UK English but as that is a personal preference I'll change the flag to the US one.

> Also to be safe: is there a reason it's still WIP?
Yes:

> Is it worth to do the language toggle at the top
Because I still have to fix this. Top right would be the intuitive placement for me as well. Kind of hesitant to mess around in someone else's css though 😅 

Also I'm not really happy with how I did things, it feels kind of hacky. I think it would be better to have a separate JSON to define the languages instead of this "auto discovery".

**Comment by h-five-e** [comment]
* switched to using a separate file to define the languages, which is a bit cleaner.
* used en-US and the US flag
* moved select to top right
* English remains default
* fixed directory structure (`/index.html` for default, `en/index.html` and `nl/index.html` for individual languages)

This means that the default language is output twice, once to `/index.html` and once to `en/index.html` which imo is an okay trade off to incorporating server configuration and the small size of the project.

**Comment by jeroenheijmans** [comment]
@LucaScorpion will you have a peek at the final changes and merge if you're good? (Since you're currently the "assigned reviewer". If you want me to help get this one across that's also fine, let me know.)

**Review by LucaScorpion — APPROVED** [review]
Looks great! :raised_hands:

Side note: I added one small thing to the gitignore to ensure it also ignored the `build/en` and `build/nl` directories.

**Pull request merged**
