### PR TITLE
Added: Light mode toggle

### LINKED ISSUE #33: Light mode based on system preferences
Currently we only have a dark mode, but using CSS Media Queries and some variables it should be relatively easy to support light mode. A manual toggle for this seems (at this moment) superfluous (though fun, at some point).

Op het moment hebben we alleen een dark mode, echter met behulp van CSS media queries en variabelen zou het ondersteunen van een light mode relatief simpel moeten zijn. Een handmatige toggle hiervoor lijkt me (op dit moment) overbodig (misschien op termijn wel leuk though).

### PR DESCRIPTION
**Pull request by drikusroor**
This PR is basicaly a continuation of #64 but has been rebased onto the latest `main` branch and therefore also adds dark/light mode support for:

- The new topic icons
- The summary toggle button in the top bar

If we still want to add the theme toggle button, I would prefer to do that in a separate follow up PR.

## UPDATE:
- I've now converted the light mode feature from one that is based on a system preference by one that is based on a toggle button persisted in local storage.

Resolves #33

### CODE REVIEW

**Comment by jeroenheijmans** [comment]
> I would prefer to do that in a separate follow up PR.

That seems fine to me, but I do still strongly prefer we create and merge that PR (into the branch for _this_ PR) before we merge into `main`. Basically [this comment from the earlier PR by David](https://github.com/infi-nl/the-infi-way/pull/64#pullrequestreview-1485054780):

> I think it's great we'll be offering a light mode version but agree that the combination of folks usually having a light themed OS and our website looking far better in dark mode is not great. Tailwindcss.com seems to have had the same consideration, and they default to dark mode with a toggle.

I think it's awesome and nice to offer a light mode, but The Infi Way looks _so_ much better in Dark mode to me that I'd prefer to default it to that and making it fully about a toggle, instead of based on the operating system.

If y'all really _do_ want to tie it into the OS setting, then I'd strongly prefer to work more on the Light Mode design and make it a bit more pleasing, on par with how good the Dark mode version is?

**Comment by drikusroor** [comment]
> I think it's awesome and nice to offer a light mode, but The Infi Way looks _so_ much better in Dark mode to me that I'd prefer to default it to that and making it fully about a toggle, instead of based on the operating system.

That's fair. I've implemented David's toggle button into the same branch in the end. Otherwise both branches would have been in my personal account and the PR would have to be done there.

**Comment by jeroenheijmans** [comment]
Cheers! Functionally the preview looks just about finished/good to me, 

One small thing I think we could still fix in the PR: the dark-mode icons in "The Infi Test" (next to the numbers of the numbered list) are the same as the light mode icons, but the Black/White should be inverted. Compare the icons to the live way.infi.nl site to see what I mean, stroke color of the icons are white in those. To clarify (left is the PR):

part of "The Infi Test" with yellow arrow pointing out the visual change

The Deploy Preview also makes me realize that I'd like to do some follow-up issue to iterate some more on the design, especially of the top(right) bar, but I'll create an issue for that later on - certainly not for this PR I think.

PS. Haven't reviewed the code, hoping you can find someone in the daily standup to do that for us?

**Comment by yougotdirked** [comment]
noice

**Pull request merged**
