### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by DannyvdSluijs**
This PR aims to add a code of conduct or at least start the dialog about whether or not we should add this in its current shape.

This `CODE_OF_CONDUCT.md` is based on the GitHub template version. I stand behind it for the majority of the contents, But I don't feel like the strict and strongly expressed **Enforcement Guidelines** are fitting with Infi. For JsonMapper I've also opted to remove that part.

### CODE REVIEW

**Review by LucaScorpion — APPROVED** [review]
Looks good, I think this would be nice to have. I have no strong opinion about removing of keeping the enforcement guidelines, so either option there is fine with me.

@jeroenheijmans it says your review is still pending, do you want to have a look/chat at/about this, or should we just merge it?

**Comment by jeroenheijmans** [comment]
Ah thanks for the ping I'd forgotten about this MR.

We have the 1.4 version of this CoC at https://con.infi.nl/code-of-conduct - I'd love to bring that up to date roughly at the same moment too. Should be easy enough to fix.

The contact e-mail address might need updating to something like `community@infi.nl` and we need to be sure multiple people monitor it since the CoC promises "prompt" action when needed. I'd love to have a short chat about that in-person or on Slack, and then (after picking the right email box) we can merge it I think.

**Review by jeroenheijmans — CHANGES_REQUESTED** [review]
(Let's tweak the contact e-mail address and ensure we monitor the mailbox with the right folks, after that it seems fine to me.)

**Review by jeroenheijmans — APPROVED** [review]

**Comment by jeroenheijmans** [comment]
We discussed this offline and fixed the support e-mail address, PR is good to go. I'll merg it.

**Pull request merged**
